config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"

  get "users/" => "users#index"
  get "users/new" => "users#new", as: :new_user
  post "users/" => "users#create"
  get "users/:id" => "users#show", as: :user
  get "users/:id/edit" => "users#edit", as: :edit_user
  patch "users/:id" => "users#update"
  delete "users/:id" => "users#destroy"

  get "reports" => "reports#index"
  get "reports/new" => "reports#new", as: :new_report
  post "users/:id/reports" => "reports#create", as: :user_reports
  get "reports/:id" => "reports#show", as: :report
  get "reports/:id/edit" => "reports#edit", as: :edit_report
  patch "reports/:id" => "reports#update"
  delete "reports/:id" => "reports#destroy"

  get "signup" => "users#new"

  get '/login'     => 'sessions#new'
  post '/login'    => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :user #sets up model relationship where a report belongs to an user.
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :reports #this sets up a relationship with the report model where a User has many reports.  
  attr_reader :password #Sets up an @password instance variable and a password getter method

  #This vaidates the name, email and password
  validates :name, presence: true #make sure name is present
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i } #make sure email is present, unique and in the correct format
  validates :password, presence: true, confirmation: true, length: { in: 6..20} #, on: :create #makes sure password is present, confirmed and 6 to 20 characters   
   
	def password=(unencrypted_password) #setter method for password.
    unless unencrypted_password.empty? #if there is no password, take the inputed password, salt and hash it.  Then set it in the record for that user.  
    @password = unencrypted_password
    self.password_digest = BCrypt::Password.create(unencrypted_password)
    end
  end

  def authenticate(unencrypted_password) #this method authenticates the password attempt.
    if BCrypt::Password.new(self.password_digest) == unencrypted_password
      return self
    else
      return false
    end
  end
end #end of the user model.  





  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #helper method current_user is defined here so that all controllers will have access to it.
  helper_method :current_user
  #set time zone to Eastern time for the strftime method.

	private 
	def current_user #helper method that helps with identifying whether a user is logged in.
	  @current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
end #end of class

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
	def index #This action is used to list reports.
		@user = current_user
		Time.zone = "Eastern Time (US & Canada)"
		#These if statements check to see if any search terms have been entered in before #returning all reports.
		if params[:student_id]
				@reports = Report.where(student_nfl_id: params[:student_id])
			elsif params[:director_flag_setting]
				@reports = Report.where(director_flag: params[:director_flag_setting])
			elsif params[:parent_flag_setting]
				@reports = Report.where(parent_flag: params[:parent_flag_setting])
			else
				@reports = Report.all
		end
	end

	def show #This action shows one report that has been id.
		@report = Report.find(params[:id]) 	
		@user = current_user
	end

	def new #This action is the first half of creating and saving a new report.
		@report = Report.new
		@user = current_user
	end

	def create #This action is the second part of creating a new report.
		@user = User.find(params[:id])
		@report = @user.reports.new(report_params)
		@report.save
		#This message flashes when a new report is saved:
		flash[:saved] = "Your report has been saved, #{@user.name}!" 
		redirect_to new_report_path(@user) #after a new report is saved the user is redirected to fresh create report page.  
	end

	def edit #This action is the first part of editing a page.  "retrives a single record"
		@report = Report.find(params[:id]) 
		@user = current_user
	end

	def update #this action saves the change in the database.
  	@report = Report.find(params[:id]) #retrives a single record
	  if @report.update_attributes(report_params)  #If a record is successfully updated, redirect to the reports index.  
	  	redirect_to reports_path
	  else
	    render :edit  #If a record is not successfully updated, render a new edit form.
	  end
	end

	def destroy #this action destroys a single record.
	  @report = Report.find(params[:id])
	  @report.destroy
	  redirect_to reports_path  #redirects to the report index.  
	end

	private #This is a private method that refactors our controller.  This method is used anytime we need to use the report parameters.  
	def report_params
		params.require(:report).permit(:student_nfl_id, :tutor_nfl_id, :what_was_covered, 
			:performance, :assignment, :director_flag, :parent_flag)
	end
end #end of controller

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new #this action renders the login page.
  end
  def create
    #Query the data base to find a record that matches the data entered into the login form.  
    user = User.where(email: params[:login][:email]).first
    if user && user.authenticate(params[:login][:password])
      # make a new key in our session object called :user_id
      # which gets stored in a cookie on our hard drive
      session[:user_id] = user.id.to_s # This is a cookie  
      redirect_to new_report_path
    else
      #flashes an error and redirects to the login page for a re-attempt.  
      flash.now[:error] = "Your email address or password are incorrect."
      render :new
    end
  end
  def destroy  #this action ends the session and redirects to the login page. 
    session.delete(:user_id)
    redirect_to login_path
  end
end #end of sessions controller

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index #this action lists all users.  
		@users = User.all
	end

	def show #this actions shows a particular record of an user.  
		@user = User.find(params[:id])
		@report = Report.new
	end

	def new #this action is the first half of createing a new user.  
    	@user = User.new
    	@report = Report.new
 	end

	def create #records the new user into the database.  
	  @user = User.new(params.require(:user).permit(:name, :email, :password, :password_confirmation))
	  if @user.save  #if the record saves, create a cookie, flash a welcome message and redirect to the new report view.  
	  	session[:user_id] = @user.id.to_s
	  	flash[:welcome] = "Thanks for signing up, #{@user.name}!"
	    redirect_to new_report_path(@user)
  	  else
    	render :new
  	  end
  	end

  	def edit #This action is the first part of editing a page.  "retrives a single record"
		@user = User.find(params[:id]) 
	end

	def update #this action saves the change in the database.
  	  @user = User.find(params[:id]) #retrives a single record
		  if @user.update_attributes(user_params)  #If a record is successfully updated, redirect to the users index.
		  	flash[:welcome] = "Your changes have been saved."  
		  	redirect_to new_report_path(@user)
		  else
		    render :edit  #If a record is not successfully updated, render a new edit form.
		end
  	end

  	def destroy #this action destroys a single record.
	  @user = User.find(params[:id])
	  @user.destroy
	  redirect_to users_path  #redirects to the report index.  
	end

	private
	def user_params
		if current_user.role == "admin"
	  		params.require(:user).permit(:name, :email, :password, :password_confirmation, :role)
	  	else
			params.require(:user).permit(:name, :email, :password, :password_confirmation)
	  	end
	end
end #end of controller

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def logged_in? #Helper method that allows us to check if there is user logged in before displaying views.
	  session[:user_id] != nil
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TutorReports</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
	<body>
		<!-- flash messages when events occur -->
		<% if flash[:welcome] %>
		    <h4 class="bg-success flash"><%= flash[:welcome] %></h4>
		<% end %>

		<% if flash[:error] %>
		    <h4 class="bg-danger flash"><%= flash[:error] %></h4>
		<% end %>

		<% if flash[:saved] %>
		    <h4 class="bg-success flash"><%= flash[:saved] %></h4>
		<% end %>

		<%= yield %>

	</body>
</html>

app/views/reports/edit.html.erb
<!-- If logged in, show this page -->
<% if logged_in? %>
  <!-- Show NavBar -->
  <%= render 'shared/navbar' %> 
  <div class="container">
      <!-- Sets bootstrap layout for this div to row -->
      <div class="row">
        <!-- column set to 4 sm col wide -->
        <div class="col-xs-8 col-xs-offset-2 col-sm-4 col-sm-offset-4">
          <section>
            <h2>Edit this report</h2>
            <!-- form-for that points specifically to the reports controller and update action -->
            <%= form_for(@report, url: {controller: "reports", action: "update"}) do |f| %>
              <!-- Student Id entry -->
              <div class="form-group">
                  <%= f.label :student_nfl_id, "Student ID #"  %>
                  <%= f.text_field :student_nfl_id, class: "form-control"  %>
              </div>
              <!-- Tutor Id entry -->
              <div class="form-group">
                  <%= f.label :tutor_nfl_id, "Tutor ID #" %>
                  <%= f.text_field :tutor_nfl_id, class: "form-control"  %>
              </div>
              <!-- What was covered entry  -->
              <div class="form-group">
                  <%= f.label :what_was_covered, "What was covered? " %>
                  <%= f.text_area :what_was_covered, class: "form-control"  %>
              </div>
              <!-- Performance entry -->
              <div class="form-group">
                  <%= f.label :performance, "Performance: " %>
                  <%= f.text_area :performance, class: "form-control"  %>
              </div>
              <!-- Assignment entry -->
              <div class="form-group">
                  <%= f.label :assignment, "Assignment: " %>
                  <%= f.text_area :assignment, class: "form-control"  %>
              </div>
              <br>
              <!-- Director flag entry -->
              <div>
                  <%= f.label :director_flag, "Does the Director need to take a look at this?" %><br>
                  <%= f.label :director_flag, "Yes", :value => true %>
                  <%= f.radio_button :director_flag, true %>
                  <%= f.label :director_flag, "No", :value => false %>
                  <%= f.radio_button :director_flag, false, :checked => true %>
              </div>
              <!-- Parent flag entry -->
              <div>
                  <%= f.label :parent_flag, "Do the Parents need to be notified?" %><br>
                  <%= f.label :parent_flag, "Yes", :value => true %>
                  <%= f.radio_button :parent_flag, true %>
                  <%= f.label :parent_flag, "No", :value => false %>
                  <%= f.radio_button :parent_flag, false, :checked => true %>
              </div>
              <!-- Submit changes button -->
              <br>
              <%= f.submit "Submit these changes", class: "btn btn-success btn-block"   %>
              <% end%>
          </section>
          <!-- If a user is not logged in, show this instead of above   -->
          <% else %>
              <h1>You are not logged in.  Please log in to access this page.</h1>
               <%= link_to 'Log In', login_path %>
          </div>
      </div>
  </div>
<% end %> <!-- end of if statement -->

    

app/views/reports/index.html.erb
<!-- If logged in, show this page -->
<% if logged_in? %>
	<!-- Show NavBar -->
	<%= render 'shared/navbar' %>
	<div class="container">
		<!-- Sets bootstrap layout for this div to row -->
	    <div class="row">
			<!-- Below are search boxes (form_tag is for passing data, form_for is for creating new instances)-->
			<!-- ******************************************************************************** -->
			<!-- Search reports by student id -->
			<%= form_tag reports_path, method: :get do  %>
				<div div class="col-md-4">
					<div>
					    <h4>Search by Student Id:</h4>
				        <%= label_tag :student_id, ""  %>
				        <%= text_field_tag :student_id%>
				    </div>
				    <br>
				    <%= submit_tag 'Search', class: "btn btn-primary" %>
				</div> 
			<% end %>
			<!-- Search reports by director flag -->
			<%= form_tag reports_path, method: :get do  %>
				<div div class="col-md-4">
					<div>
						<h4>Search by Director flag:</h4>
				        <%= label_tag :director_flag_setting, "" %>
				        <%= text_field_tag :director_flag_setting %>
				    </div>
				    <br>
				    <%= submit_tag 'Search', class: "btn btn-primary" %>
				</div>
			<% end %>
		 	<!-- Search reports by parent flag -->
			<%= form_tag reports_path, method: :get do  %>
				<div div class="col-md-4">
					<div>
						<h4>Search by Parent flag:</h4>
					    <%= label_tag :parent_flag_setting, "" %>
					    <%= text_field_tag :parent_flag_setting %>
				    </div>
				    <br>
				    <%= submit_tag 'Search', class: "btn btn-primary" %>
				</div>   
			<% end %>
			<!-- ********************************************************************************* -->
		   	<!-- Show a list of all reports starting from the newest to oldest-->
			</div>
				<section>
					<div class="row">
						<h3>Reports:</h3>
						<% @reports.reverse.each do |report| %>
							<div class="col-md-4">
								<p><strong>Report on Student Id # <%=report.student_nfl_id%> </strong></p>
								<p><strong>Written by Tutor Id #: <%=report.tutor_nfl_id%> </strong></p>
								<p><strong>Created at:</strong> <%= report.created_at.strftime("%I:%M%p on %m/%d/%y") %></p>
								<p><strong>What was covered:</strong> <%= report.what_was_covered %></p>
							    <p><strong>Performance:</strong> <%= report.performance %></p>
							    <p><strong>Assignment:</strong> <%= report.assignment %></p>
								<p><strong>Director flag:</strong> <%= report.director_flag%></p>
								<p><strong>Parent flag:</strong> <%= report.parent_flag %></p>
								<% if current_user.role == "admin" %> 
								<!-- edit button -->
								<%= link_to "Edit this report", edit_report_path(report), class: "btn btn-info" %>
								<!-- delete button -->
								<%= link_to "Delete this report", report_path(report), method: :delete, data: { confirm: "Are you sure you want to delete this report?"}, class: "btn btn-danger"  %>
								<% end %><!-- end admin if statement from above -->
								<br><br>
							</div>
						<% end %>
					</div>
				</section>
			<% else %>
			<h1>You are not logged in.  Please log in to access this page.</h1>
		    <%= link_to 'Log In', login_path %>
	</div>
<% end %>

app/views/reports/new.html.erb
<!-- If logged in, show this page -->
<% if logged_in? %>
  <!-- Show NavBar --> 
  <%= render 'shared/navbar' %> 
  <div class="container">
    <!-- Sets bootstrap layout for this div to row -->
    <div class="row">
      <!-- column set to 4 sm col wide -->
      <div class="col-xs-8 col-xs-offset-2 col-sm-4 col-sm-offset-4">
        <section>
          <h2>Add a New Report</h2>
          <!-- form-for that takes in @user and @report -->
          <%= form_for [@user, @report] do |f| %>
            <!-- Student Id entry -->
            <div class="form-group">
              <%= f.label :student_nfl_id, "Student ID #"  %>
              <%= f.text_field :student_nfl_id, class: "form-control" %>
            </div>
            <!-- Tutor Id entry -->
            <div class="form-group">
              <%= f.label :tutor_nfl_id, "Tutor ID #" %>
              <%= f.text_field :tutor_nfl_id, class: "form-control" %>
            </div>
            <!-- What was covered entry  -->
            <div class="form-group">
                  <%= f.label :what_was_covered, "What was covered? " %>
                  <%= f.text_area :what_was_covered, class: "form-control" %>
            </div>
            <!-- Performance entry -->
            <div class="form-group">
              <%= f.label :performance, "Performance: " %>
              <%= f.text_area :performance, class: "form-control" %>
            </div>
            <!-- Assignment entry -->
            <div class="form-group">
              <%= f.label :assignment, "Assignment: " %>
              <%= f.text_area :assignment, class: "form-control" %>
            </div>
            <br>
            <!-- Director flag entry -->
            <div class="form-group">
              <%= f.label :director_flag, "Does the Director need to take a look at this?" %><br>
              <%= f.label :director_flag, "Yes", :value => true %>
              <%= f.radio_button :director_flag, true %>
              <%= f.label :director_flag, "No", :value => false %>
              <%= f.radio_button :director_flag, false, :checked => true %>
            </div>
            <!-- Parent flag entry -->
            <div class="form-group">
              <%= f.label :parent_flag, "Do the Parents need to be notified?" %><br>
              <%= f.label :parent_flag, "Yes", :value => true %>
              <%= f.radio_button :parent_flag, true %>
              <%= f.label :parent_flag, "No", :value => false %>
              <%= f.radio_button :parent_flag, false, :checked => true %>
            </div>
            <!-- Submit changes button -->
            <br>
            <%= f.submit "Add new report", class: "btn btn-success btn-block"  %>
            <% end%>
        </section>
        <!-- If a user is not logged in, show this instead of above   -->
        <% else %>
          <h1>You are not logged in.  Please log in to access this page.</h1>
          <%= link_to 'Log In', login_path %>
      </div>
    </div>
  </div>
<% end %>

app/views/reports/show.html.erb
<!-- If logged in, show this page -->
<% if logged_in? %>
	<!-- Show NavBar --> 
	<%= render 'shared/navbar' %> 
	<div class="col-md-8">
		<!-- display report details -->
		<h1>Report Details:</h1>
		<p><strong>Student ID #: </strong><%= @report.student_nfl_id %> <br><br>
		<strong>Created at:</strong> <%= @report.created_at.strftime("%I:%M%p on %m/%d/%y") %><br><br>
		<strong>What was covered:</strong> <%= @report.what_was_covered %><br><br>
		<strong>Performance:</strong> <%= @report.performance %><br><br>
		<strong>Assignment:</strong> <%= @report.assignment %><br><br>
		<strong>Director flag:</strong> <%= @report.director_flag%><br><br>
		<strong>Parent flag:</strong> <%= @report.parent_flag %>
		</p>
		<!-- Show the section below if the user logged in as admin -->
		<% if current_user.role == "admin" %> 
		<!-- edit button -->
		<%= link_to "Edit this report", edit_report_path(@report), class: "btn btn-warning" %>
		<!-- delete button -->
		<%= link_to "Delete this report", report_path, method: :delete, data: { confirm: "Are you sure you want to delete this report?"}, class: "btn btn-danger"  %>
		<% end %><!-- end admin if statement from above -->
	</div>
	<!-- If not logged in, show this page -->
	<% else %>
        <h1>You are not logged in.  Please log in to access this page.</h1>
        <%= link_to 'Log In', login_path %>
<% end %>

app/views/shared/_login_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    	<!-- logo image -->
		<%= image_tag("logo_4NF.jpg", size: "50x50")  %>
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    	<!-- logo image -->
  		<%= image_tag("logo_4NF.jpg", size: "50x50")  %>
      <!-- shows who is logged in -->
  		<span>Logged in as: <%= current_user.name %></span>
      <!-- navbar links -->
      <ul class="nav navbar-nav navbar-right">       
        <li><%= link_to "List of Reports", reports_path %></li>
        <li><%= link_to "Create a new report", new_report_path%></li>
        <li><%= link_to "Your Profile", user_path(current_user.id)%></li>
        <!-- If the user is an admin, show list of users link -->
        <% if current_user.role == "admin" %> 
          <li><%= link_to "List of users", users_path%></li>
        <% end %>
        <!-- logout button -->
        <li><%= link_to 'Log Out', logout_path, method: :delete, class: "btn btn-warning btn-block" %></li>	
      </ul>
  </div><!-- /.container-fluid -->
</nav>

app/views/users/edit.html.erb
<% if logged_in? %>
  <!-- Show NavBar -->
  <%= render 'shared/navbar' %> 
  <div class="container">
      <!-- Sets bootstrap layout for this div to row -->
      <div class="row">
        <!-- column set to 4 sm col wide -->
        <div class="col-xs-8 col-xs-offset-2 col-sm-4 col-sm-offset-4">
          <section>
            <!-- show this title if admin -->
            <% if current_user.role == "admin" %> 
            <h2>Edit this User</h2>
            <!-- show this title if tutor -->
            <% else %>
            <h2>Edit your profile</h2>
            <% end %>
            <!-- if any errors with user sign up show the following warnings -->
            <% if @user.errors.any? %>
              <div>
                <h4 class="text-danger"><%= pluralize(@user.errors.count, "error") %> prevented you from changing the account:</h4>
                <ul class="list-group">
                  <% @user.errors.full_messages.each do |msg| %>   
                    <li class="list-group-item list-group-item-danger"><%= msg.downcase %></li>
                  <% end %>
                </ul>            
              </div>
            <% end %>
            <!-- form-for that points specifically to the reports controller and update action -->
            <%= form_for(@user, url: {controller: "users", action: "update"}) do |f| %>
              <!-- name entry -->
            <div class="form-group">
              <%= f.label :name %>
              <%= f.text_field :name, class: "form-control"   %>
            </div>
            <!-- email entry -->
            <div class="form-group">
              <%= f.label :email %>
              <%= f.text_field :email, class: "form-control"   %>
            </div>
            <!-- password entry -->
            <div class="form-group">
              <%= f.label :password, "New Password" %>
              <%= f.password_field :password, class: "form-control"  %>
            </div>
            <!-- password confirmation -->
            <div class="form-group">
              <%= f.label :password_confirmation %>
              <%= f.password_field :password_confirmation, class: "form-control"  %>
            </div>
            <!-- show this option if admin -->
            <% if current_user.role == "admin" %> 
            <div class="form-group">
              <%= f.label :role, "Update role to admin" %>
              <%= f.text_field :role, class: "form-control"  %>
            </div>
            <% end %>
              <!-- Submit changes button -->
            <br>
            <%= f.submit "Submit these changes", class: "btn btn-success btn-block"   %>
            <% end%>
          </section>
          <!-- If a user is not logged in, show this instead of above   -->
          <% else %>
              <h1>You are not logged in.  Please log in to access this page.</h1>
               <%= link_to 'Log In', login_path %>
          </div>
      </div>
  </div>
<% end %> <!-- end of if statement -->

app/views/users/index.html.erb
<!-- If logged in, show this page -->
<% if logged_in? %>
	<!-- Show NavBar --> 
	<%= render 'shared/navbar' %> 
	<div class="col-md-8">
		<!-- Show the section below if the user logged in as admin -->
		<% if current_user.role == "admin" %> 
			<h1>App Users:</h1>
				<ul>
					<!-- lists all users -->
					<% @users.each do |user| %>
					<li>
						<strong><%= user.name %></strong>
						<%= link_to "More info", user_path(user) %> <!-- link helper method -->
					</li>
					<% end %>
				</ul>
		<% else %>
			<strong><%= @users.name %></strong>
			<%= link_to "More info", user_path(current_user.id)%>
		<% end %>
	</div>
<!-- If not logged in, show this page -->
<% else %>
		<h1>You are not logged in.  Please log in to access this page.</h1>
	  	<%= link_to 'Log In', login_path %>
<% end %>

app/views/users/new.html.erb
<!-- Show NavBar -->
<%= render 'shared/login_navbar' %> 

<div class="container">
  <div class="col-xs-8 col-xs-offset-2 col-sm-4 col-sm-offset-4">

    <h1>NFLC Tutor Sign Up</h1>
    <!-- if any errors with user sign up show the followingg warnings -->
    <% if @user.errors.any? %>
      <div>
        <h4 class="text-danger"><%= pluralize(@user.errors.count, "error") %> prevented you from signing up for an account:</h4>
        <ul class="list-group">
          <% @user.errors.full_messages.each do |msg| %>   
            <li class="list-group-item list-group-item-danger"><%= msg.downcase %></li>
          <% end %>
        </ul>            
      </div>
    <% end %>
    <!-- form for signing up -->
    <%= form_for @user do |f| %>
      <!-- name entry -->
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control"   %>
      </div>
      <!-- email entry -->
      <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: "form-control"   %>
      </div>
      <!-- password entry -->
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control"  %>
      </div>
      <!-- password confirmation -->
      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: "form-control"  %>
      </div>
      <!-- sign up button -->
      <div>
        <%= f.submit "Sign up", class: "btn btn-success btn-block" %>
      </div>
    <% end %>
    <br>
    <div>
      <!-- already have account button -->
      <%= link_to 'Have an Account already?  Log in', login_path, class: "btn btn-primary btn-block"  %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<!-- If logged in, show this page -->
<% if logged_in? %>
	<!-- show the login navbar -->
	<%= render 'shared/navbar' %> 
	<div class="col-md-8">
		<!-- Show the section below if the user logged in as admin -->
		<% if current_user.role == "admin" %> 
			<section>
				<h1><%= current_user.name %></h1>
				<p><strong>Name: </strong><%= @user.name %></p>
				<p><strong>Email: </strong><%= @user.email%></p>
				<!-- edit button -->
			<%= link_to "Edit this user", edit_user_path(@user), class: "btn btn-primary" %>
			<!-- delete button -->
			<%#= link_to "Delete this user", user_path, method: :delete, data: { confirm: "Are you sure you want to delete this user?"}, class: "btn btn-danger"  %>
			</section>
		<% else %>
			<section>
				<p><strong>Name: </strong><%= @user.name %></p>
				<p><strong>Email: </strong><%= @user.email%></p>
				<!-- edit button -->
			<%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-primary" %>
			<!-- delete button -->
			<%#= link_to "Delete your profile", user_path, method: :delete, data: { confirm: "Are you sure you want to delete this user?"}, class: "btn btn-danger"  %>
			</section>
		<% end %>
	</div>
<!-- If not logged in, show this page -->
<% else %>
	<h1>You are not logged in.  Please log in to access this page.</h1>
  	<%= link_to 'Log In', login_path %>
<% end %>